url: "https://aet21.github.io"
# baseurl: "/aet21.github.io"
baseurl: ""

repository: "aet21/aet21.github.io"

plugins:
  - jekyll-github-metadata

collections:
  people:
    output: true
  papers:
    output: true
  projects:
    output: true
  software:
    output: true