url: "https://aet21.github.io"
#baseurl: "/aet21.github.io" 
baseurl: ""

repository: aet21/aet21.github.io

plugins:
  # - jekyll-gzip
  - jekyll-github-metadata

collections:
  people:
    output: true
  papers:
    output: true
<<<<<<< HEAD
  projects:
    output: true
  software:
    output: true
=======
>>>>>>> 58a8021 (Update paper page)
